# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://hasban-fardani.github.io/blog"  # Include trailing slash
title = "Hasban blog"
copyright = "Copyright © 2022 "
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = "hasban-blog"

DefaultContentLanguage = "id"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "Kategori"
tag = "tag"
series = "seri"

[outputs]
home = ["HTML", "RSS", "JSON"]
